@startuml Classes

class Controller {
    + void setup()
    + void update()
}

class MessageHandler {
    + void onMessage<Message>(void* handler)
}

class Sensor {
    + void setup()
    + void update()
}

class CANBusController {
}

class RadioModuleController {
    + void sendMessage()
}

class SDCardController {
    + fileptr openFile(filename)
    + void write(fileptr)
    + void read(fileptr)
    + void close(fileptr)
    + void writeCanMessage()
    + void writeRadioMessage()
}

class Message {
    + int id
}

class CANMessage {}

class RadioMesaage {}

Sensor <|-- GPS 
Message <|-- CANMessage
Message <|-- RadioMesaage
Controller <|-- CANBusController
MessageHandler <|-- CANBusController
Controller <|-- RadioModuleController
MessageHandler <|-- RadioModuleController
Controller <|-- SDCardController


@enduml